# fly.toml app configuration file generated for northeption-sns-bot on 2026-05-28T19:39:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'northeption-sns-bot'
primary_region = 'nrt'

[build]

[processes]
  app = 'node index.js'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "schedule_data"
  destination = "/data"
